# Generated by Django 3.2.16 on 2022-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_post_icerik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icerik',
            field=models.TextField(max_length=10000),
        ),
    ]
