# Generated by Django 3.2.16 on 2022-11-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_post_icerik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='isim')),
                ('yorum', models.TextField(max_length=400, verbose_name='Yorum')),
                ('yorumTarih', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Yorum', to='myApp.post')),
            ],
        ),
    ]
