# Generated by Django 3.2.16 on 2022-11-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0006_alter_yorum_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='kullanici',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
