# Generated by Django 3.2.16 on 2022-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20221120_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Kullanici',
            new_name='kullanici',
        ),
    ]
