# Generated by Django 3.2.16 on 2022-11-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_rename_kullanici_like_kullanici'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
    ]
