# Generated by Django 3.2.16 on 2022-11-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20221120_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
