# Generated by Django 3.2.16 on 2022-11-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profil_resim',
            field=models.ImageField(blank=True, null=True, upload_to='posts/profil_resim/'),
        ),
    ]
