# Generated by Django 3.2.16 on 2022-11-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_post_olusturan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profil_resim',
            field=models.ImageField(blank=True, default='posts/profil_resim/default.jpg', null=True, upload_to='posts/profil_resim/'),
        ),
    ]
