# Generated by Django 3.2.16 on 2022-11-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0021_alter_profile_profil_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profil',
        ),
        migrations.AddField(
            model_name='profile',
            name='isim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kullanici',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
