# Generated by Django 3.2.16 on 2022-11-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_auto_20221124_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isim',
        ),
    ]
