# Generated by Django 3.2.16 on 2023-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_auto_20221212_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('takipci', models.ManyToManyField(related_name='_myApp_hesap_takipci_+', to='myApp.Hesap')),
            ],
        ),
    ]
