# Generated by Django 3.2.16 on 2023-01-11 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0028_hesap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='takipci',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
