# Generated by Django 3.2.16 on 2023-01-11 17:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_profile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icerik',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
